// Code generated by update_ips.go. DO NOT EDIT.

package cloudflareip

import (
	"net/netip"

	"github.com/gaissmai/cidrtree"
)

var cidrTbl = new(cidrtree.Table[IPRange])

func init() {
	var r IPRange
	r = IPRange{
		Prefix: netip.MustParsePrefix("173.245.48.0/20"),
	}
	cidrTbl.Insert(r.Prefix, r)
	r = IPRange{
		Prefix: netip.MustParsePrefix("103.21.244.0/22"),
	}
	cidrTbl.Insert(r.Prefix, r)
	r = IPRange{
		Prefix: netip.MustParsePrefix("103.22.200.0/22"),
	}
	cidrTbl.Insert(r.Prefix, r)
	r = IPRange{
		Prefix: netip.MustParsePrefix("103.31.4.0/22"),
	}
	cidrTbl.Insert(r.Prefix, r)
	r = IPRange{
		Prefix: netip.MustParsePrefix("141.101.64.0/18"),
	}
	cidrTbl.Insert(r.Prefix, r)
	r = IPRange{
		Prefix: netip.MustParsePrefix("108.162.192.0/18"),
	}
	cidrTbl.Insert(r.Prefix, r)
	r = IPRange{
		Prefix: netip.MustParsePrefix("190.93.240.0/20"),
	}
	cidrTbl.Insert(r.Prefix, r)
	r = IPRange{
		Prefix: netip.MustParsePrefix("188.114.96.0/20"),
	}
	cidrTbl.Insert(r.Prefix, r)
	r = IPRange{
		Prefix: netip.MustParsePrefix("197.234.240.0/22"),
	}
	cidrTbl.Insert(r.Prefix, r)
	r = IPRange{
		Prefix: netip.MustParsePrefix("198.41.128.0/17"),
	}
	cidrTbl.Insert(r.Prefix, r)
	r = IPRange{
		Prefix: netip.MustParsePrefix("162.158.0.0/15"),
	}
	cidrTbl.Insert(r.Prefix, r)
	r = IPRange{
		Prefix: netip.MustParsePrefix("104.16.0.0/13"),
	}
	cidrTbl.Insert(r.Prefix, r)
	r = IPRange{
		Prefix: netip.MustParsePrefix("104.24.0.0/14"),
	}
	cidrTbl.Insert(r.Prefix, r)
	r = IPRange{
		Prefix: netip.MustParsePrefix("172.64.0.0/13"),
	}
	cidrTbl.Insert(r.Prefix, r)
	r = IPRange{
		Prefix: netip.MustParsePrefix("2400:cb00::/32"),
	}
	cidrTbl.Insert(r.Prefix, r)
	r = IPRange{
		Prefix: netip.MustParsePrefix("2606:4700::/32"),
	}
	cidrTbl.Insert(r.Prefix, r)
	r = IPRange{
		Prefix: netip.MustParsePrefix("2803:f800::/32"),
	}
	cidrTbl.Insert(r.Prefix, r)
	r = IPRange{
		Prefix: netip.MustParsePrefix("2405:b500::/32"),
	}
	cidrTbl.Insert(r.Prefix, r)
	r = IPRange{
		Prefix: netip.MustParsePrefix("2405:8100::/32"),
	}
	cidrTbl.Insert(r.Prefix, r)
	r = IPRange{
		Prefix: netip.MustParsePrefix("2a06:98c0::/29"),
	}
	cidrTbl.Insert(r.Prefix, r)
}
